### ISSUE TITLE
1.5.2 Hopper in minecart bugs

### ISSUE THREAD

**Issue by undeadbanana** [matthewbot/PrisonPearl#9]
Placing an active prison pearl within a Hopper will treat it as though nobody is carrying it but the pearl will still remain within the container.

Upon typing /pplocate, the prisoner will be freed but the prison pearl will remain behind complete with description. Example: I pearl JoeSchmoe and put his pearl within a hopper. He types /pplocate and is released. His pearl is still within the hopper, completely with description on the pearl. (JoeSchmoe contained within this pearl). I pearl him again and repeat my mistake. He does the same and another pearl is within the chest with his name and all. The pearls that are left behind cannot be used by the PrisonPearl system, as the prisoner is free. Or used as a regular pearl.

**Comment by ghost** [comment]
That's not really his pearl, it's just an ender pearl with the name and lore. There are other ways to produce the same problem.
